use crate::config::ServiceKind;

use super::SafetyRow;

const KIND: ServiceKind = ServiceKind::Overseerr;

pub(super) const ROWS: &[SafetyRow] = &[
    SafetyRow::new(KIND, "post_auth_local", false),
    SafetyRow::new(KIND, "post_auth_logout", false),
    SafetyRow::new(KIND, "post_auth_plex", false),
    SafetyRow::new(KIND, "post_auth_reset_password", false),
    SafetyRow::new(KIND, "post_auth_reset_password_by_guid", false),
    SafetyRow::new(KIND, "post_issue", false),
    SafetyRow::new(KIND, "post_issue_by_issue_id_status", false),
    SafetyRow::new(KIND, "post_issue_comment_by_issue_id", false),
    SafetyRow::new(KIND, "post_media_by_media_id_status", false),
    SafetyRow::new(KIND, "post_request", false),
    SafetyRow::new(KIND, "post_request_by_request_id_status", false),
    SafetyRow::new(KIND, "post_request_retry_by_request_id", false),
    SafetyRow::new(KIND, "post_settings_cache_flush_by_cache_id", false),
    SafetyRow::new(KIND, "post_settings_discover", false),
    SafetyRow::new(KIND, "post_settings_discover_add", false),
    SafetyRow::new(KIND, "post_settings_initialize", false),
    SafetyRow::new(KIND, "post_settings_jobs_cancel_by_job_id", false),
    SafetyRow::new(KIND, "post_settings_jobs_run_by_job_id", false),
    SafetyRow::new(KIND, "post_settings_jobs_schedule_by_job_id", false),
    SafetyRow::new(KIND, "post_settings_main", false),
    SafetyRow::new(KIND, "post_settings_main_regenerate", false),
    SafetyRow::new(KIND, "post_settings_notifications_discord", false),
    SafetyRow::new(KIND, "post_settings_notifications_discord_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_email", false),
    SafetyRow::new(KIND, "post_settings_notifications_email_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_gotify", false),
    SafetyRow::new(KIND, "post_settings_notifications_gotify_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_lunasea", false),
    SafetyRow::new(KIND, "post_settings_notifications_lunasea_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_pushbullet", false),
    SafetyRow::new(KIND, "post_settings_notifications_pushbullet_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_pushover", false),
    SafetyRow::new(KIND, "post_settings_notifications_pushover_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_slack", false),
    SafetyRow::new(KIND, "post_settings_notifications_slack_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_telegram", false),
    SafetyRow::new(KIND, "post_settings_notifications_telegram_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_webhook", false),
    SafetyRow::new(KIND, "post_settings_notifications_webhook_test", false),
    SafetyRow::new(KIND, "post_settings_notifications_webpush", false),
    SafetyRow::new(KIND, "post_settings_notifications_webpush_test", false),
    SafetyRow::new(KIND, "post_settings_plex", false),
    SafetyRow::new(KIND, "post_settings_plex_sync", false),
    SafetyRow::new(KIND, "post_settings_radarr", false),
    SafetyRow::new(KIND, "post_settings_radarr_test", false),
    SafetyRow::new(KIND, "post_settings_sonarr", false),
    SafetyRow::new(KIND, "post_settings_sonarr_test", false),
    SafetyRow::new(KIND, "post_settings_tautulli", false),
    SafetyRow::new(KIND, "post_user", false),
    SafetyRow::new(KIND, "post_user_import_from_plex", false),
    SafetyRow::new(KIND, "post_user_register_push_subscription", false),
    SafetyRow::new(KIND, "post_user_settings_main_by_user_id", false),
    SafetyRow::new(KIND, "post_user_settings_notifications_by_user_id", false),
    SafetyRow::new(KIND, "post_user_settings_password_by_user_id", false),
    SafetyRow::new(KIND, "post_user_settings_permissions_by_user_id", false),
    SafetyRow::new(KIND, "put_issue_comment_by_comment_id", false),
    SafetyRow::new(KIND, "put_request_by_request_id", false),
    SafetyRow::new(KIND, "put_settings_discover_by_slider_id", false),
    SafetyRow::new(KIND, "put_settings_radarr_by_radarr_id", false),
    SafetyRow::new(KIND, "put_settings_sonarr_by_sonarr_id", false),
    SafetyRow::new(KIND, "put_user", false),
    SafetyRow::new(KIND, "put_user_by_user_id", false),
];

#[cfg(test)]
#[path = "overseerr_tests.rs"]
mod tests;
