use crate::config::ServiceKind;

use super::SafetyRow;

const KIND: ServiceKind = ServiceKind::Plex;

pub(super) const ROWS: &[SafetyRow] = &[
    SafetyRow::new(KIND, "add_collection_items", false),
    SafetyRow::new(KIND, "add_device", false),
    SafetyRow::new(KIND, "add_device_to_dvr", false),
    SafetyRow::new(KIND, "add_download_queue_items", false),
    SafetyRow::new(KIND, "add_extras", false),
    SafetyRow::new(KIND, "add_lineup", false),
    SafetyRow::new(KIND, "add_playlist_items", false),
    SafetyRow::new(KIND, "add_provider", false),
    SafetyRow::new(KIND, "add_section", false),
    SafetyRow::new(KIND, "add_to_play_queue", false),
    SafetyRow::new(KIND, "analyze_metadata", false),
    SafetyRow::new(KIND, "apply_updates", false),
    SafetyRow::new(KIND, "check_updates", false),
    SafetyRow::new(KIND, "clean_bundles", false),
    SafetyRow::new(KIND, "create_collection", false),
    SafetyRow::new(KIND, "create_custom_hub", false),
    SafetyRow::new(KIND, "create_download_queue", false),
    SafetyRow::new(KIND, "create_dvr", false),
    SafetyRow::new(KIND, "create_marker", false),
    SafetyRow::new(KIND, "create_play_queue", false),
    SafetyRow::new(KIND, "create_playlist", false),
    SafetyRow::new(KIND, "create_subscription", false),
    SafetyRow::new(KIND, "delete_collection_item", false),
    SafetyRow::new(KIND, "detect_ads", false),
    SafetyRow::new(KIND, "detect_credits", false),
    SafetyRow::new(KIND, "detect_intros", false),
    SafetyRow::new(KIND, "detect_voice_activity", false),
    SafetyRow::new(KIND, "discover_devices", false),
    SafetyRow::new(KIND, "edit_marker", false),
    SafetyRow::new(KIND, "edit_metadata_item", false),
    SafetyRow::new(KIND, "edit_section", false),
    SafetyRow::new(KIND, "edit_subscription_preferences", false),
    SafetyRow::new(KIND, "empty_trash", false),
    SafetyRow::new(KIND, "enable_papertrail", false),
    SafetyRow::new(KIND, "generate_thumbs", false),
    SafetyRow::new(KIND, "get_transient_token", false),
    SafetyRow::new(KIND, "ingest_transient_item", false),
    SafetyRow::new(KIND, "list_matches", false),
    SafetyRow::new(KIND, "mark_played", false),
    SafetyRow::new(KIND, "match_item", false),
    SafetyRow::new(KIND, "merge_items", false),
    SafetyRow::new(KIND, "modify_device", false),
    SafetyRow::new(KIND, "modify_playlist_generator", false),
    SafetyRow::new(KIND, "move_collection_item", false),
    SafetyRow::new(KIND, "move_hub", false),
    SafetyRow::new(KIND, "move_play_queue_item", false),
    SafetyRow::new(KIND, "move_playlist_item", false),
    SafetyRow::new(KIND, "optimize_database", false),
    SafetyRow::new(KIND, "post_users_sign_in_data", false),
    SafetyRow::new(KIND, "process_subscriptions", false),
    SafetyRow::new(KIND, "refresh_items_metadata", false),
    SafetyRow::new(KIND, "refresh_playlist", false),
    SafetyRow::new(KIND, "refresh_providers", false),
    SafetyRow::new(KIND, "refresh_section", false),
    SafetyRow::new(KIND, "refresh_sections_metadata", false),
    SafetyRow::new(KIND, "reload_guide", false),
    SafetyRow::new(KIND, "reorder_subscription", false),
    SafetyRow::new(KIND, "report", false),
    SafetyRow::new(KIND, "reset_play_queue", false),
    SafetyRow::new(KIND, "restart_processing_download_queue_items", false),
    SafetyRow::new(KIND, "scan", false),
    SafetyRow::new(KIND, "set_channelmap", false),
    SafetyRow::new(KIND, "set_device_preferences", false),
    SafetyRow::new(KIND, "set_dvr_preferences", false),
    SafetyRow::new(KIND, "set_item_artwork", false),
    SafetyRow::new(KIND, "set_item_preferences", false),
    SafetyRow::new(KIND, "set_preferences", false),
    SafetyRow::new(KIND, "set_rating", false),
    SafetyRow::new(KIND, "set_section_preferences", false),
    SafetyRow::new(KIND, "set_stream_offset", false),
    SafetyRow::new(KIND, "set_stream_selection", false),
    SafetyRow::new(KIND, "shuffle", false),
    SafetyRow::new(KIND, "split_item", false),
    SafetyRow::new(KIND, "start_analysis", false),
    SafetyRow::new(KIND, "start_bif_generation", false),
    SafetyRow::new(KIND, "start_task", false),
    SafetyRow::new(KIND, "start_tasks", false),
    SafetyRow::new(KIND, "terminate_session", true),
    SafetyRow::new(KIND, "trigger_fallback", false),
    SafetyRow::new(KIND, "tune_channel", false),
    SafetyRow::new(KIND, "unmatch", false),
    SafetyRow::new(KIND, "unscrobble", false),
    SafetyRow::new(KIND, "unshuffle", false),
    SafetyRow::new(KIND, "update_hub_visibility", false),
    SafetyRow::new(KIND, "update_item_artwork", false),
    SafetyRow::new(KIND, "update_items", false),
    SafetyRow::new(KIND, "update_playlist", false),
    SafetyRow::new(KIND, "upload_playlist", false),
    SafetyRow::new(KIND, "write_log", false),
    SafetyRow::new(KIND, "write_message", false),
];

#[cfg(test)]
#[path = "plex_tests.rs"]
mod tests;
