use crate::config::ServiceKind;

use super::SafetyRow;

const KIND: ServiceKind = ServiceKind::Sonarr;

pub(super) const ROWS: &[SafetyRow] = &[
    SafetyRow::new(KIND, "post_autotagging", false),
    SafetyRow::new(KIND, "post_command", false),
    SafetyRow::new(KIND, "post_customfilter", false),
    SafetyRow::new(KIND, "post_customformat", false),
    SafetyRow::new(KIND, "post_delayprofile", false),
    SafetyRow::new(KIND, "post_downloadclient", false),
    SafetyRow::new(KIND, "post_downloadclient_action_by_name", false),
    SafetyRow::new(KIND, "post_downloadclient_test", false),
    SafetyRow::new(KIND, "post_downloadclient_testall", false),
    SafetyRow::new(KIND, "post_history_failed_by_id", false),
    SafetyRow::new(KIND, "post_importlist", false),
    SafetyRow::new(KIND, "post_importlist_action_by_name", false),
    SafetyRow::new(KIND, "post_importlist_test", false),
    SafetyRow::new(KIND, "post_importlist_testall", false),
    SafetyRow::new(KIND, "post_importlistexclusion", false),
    SafetyRow::new(KIND, "post_indexer", false),
    SafetyRow::new(KIND, "post_indexer_action_by_name", false),
    SafetyRow::new(KIND, "post_indexer_test", false),
    SafetyRow::new(KIND, "post_indexer_testall", false),
    SafetyRow::new(KIND, "post_languageprofile", false),
    SafetyRow::new(KIND, "post_login", false),
    SafetyRow::new(KIND, "post_manualimport", false),
    SafetyRow::new(KIND, "post_metadata", false),
    SafetyRow::new(KIND, "post_metadata_action_by_name", false),
    SafetyRow::new(KIND, "post_metadata_test", false),
    SafetyRow::new(KIND, "post_metadata_testall", false),
    SafetyRow::new(KIND, "post_notification", false),
    SafetyRow::new(KIND, "post_notification_action_by_name", false),
    SafetyRow::new(KIND, "post_notification_test", false),
    SafetyRow::new(KIND, "post_notification_testall", false),
    SafetyRow::new(KIND, "post_qualityprofile", false),
    SafetyRow::new(KIND, "post_queue_grab_bulk", false),
    SafetyRow::new(KIND, "post_queue_grab_by_id", false),
    SafetyRow::new(KIND, "post_release", false),
    SafetyRow::new(KIND, "post_release_push", false),
    SafetyRow::new(KIND, "post_releaseprofile", false),
    SafetyRow::new(KIND, "post_remotepathmapping", false),
    SafetyRow::new(KIND, "post_rootfolder", false),
    SafetyRow::new(KIND, "post_seasonpass", false),
    SafetyRow::new(KIND, "post_series", false),
    SafetyRow::new(KIND, "post_series_import", false),
    SafetyRow::new(KIND, "post_system_backup_restore_by_id", false),
    SafetyRow::new(KIND, "post_system_backup_restore_upload", false),
    SafetyRow::new(KIND, "post_system_restart", false),
    SafetyRow::new(KIND, "post_system_shutdown", false),
    SafetyRow::new(KIND, "post_tag", false),
    SafetyRow::new(KIND, "put_autotagging_by_id", false),
    SafetyRow::new(KIND, "put_config_downloadclient_by_id", false),
    SafetyRow::new(KIND, "put_config_host_by_id", false),
    SafetyRow::new(KIND, "put_config_importlist_by_id", false),
    SafetyRow::new(KIND, "put_config_indexer_by_id", false),
    SafetyRow::new(KIND, "put_config_mediamanagement_by_id", false),
    SafetyRow::new(KIND, "put_config_naming_by_id", false),
    SafetyRow::new(KIND, "put_config_ui_by_id", false),
    SafetyRow::new(KIND, "put_customfilter_by_id", false),
    SafetyRow::new(KIND, "put_customformat_bulk", false),
    SafetyRow::new(KIND, "put_customformat_by_id", false),
    SafetyRow::new(KIND, "put_delayprofile_by_id", false),
    SafetyRow::new(KIND, "put_delayprofile_reorder_by_id", false),
    SafetyRow::new(KIND, "put_downloadclient_bulk", false),
    SafetyRow::new(KIND, "put_downloadclient_by_id", false),
    SafetyRow::new(KIND, "put_episode_by_id", false),
    SafetyRow::new(KIND, "put_episode_monitor", false),
    SafetyRow::new(KIND, "put_episodefile_bulk", false),
    SafetyRow::new(KIND, "put_episodefile_by_id", false),
    SafetyRow::new(KIND, "put_episodefile_editor", false),
    SafetyRow::new(KIND, "put_importlist_bulk", false),
    SafetyRow::new(KIND, "put_importlist_by_id", false),
    SafetyRow::new(KIND, "put_importlistexclusion_by_id", false),
    SafetyRow::new(KIND, "put_indexer_bulk", false),
    SafetyRow::new(KIND, "put_indexer_by_id", false),
    SafetyRow::new(KIND, "put_languageprofile_by_id", false),
    SafetyRow::new(KIND, "put_metadata_by_id", false),
    SafetyRow::new(KIND, "put_notification_by_id", false),
    SafetyRow::new(KIND, "put_qualitydefinition_by_id", false),
    SafetyRow::new(KIND, "put_qualitydefinition_update", false),
    SafetyRow::new(KIND, "put_qualityprofile_by_id", false),
    SafetyRow::new(KIND, "put_releaseprofile_by_id", false),
    SafetyRow::new(KIND, "put_remotepathmapping_by_id", false),
    SafetyRow::new(KIND, "put_series_by_id", false),
    SafetyRow::new(KIND, "put_series_editor", false),
    SafetyRow::new(KIND, "put_tag_by_id", false),
];

#[cfg(test)]
#[path = "sonarr_tests.rs"]
mod tests;
