name: MSRV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  msrv:
    name: Minimum Supported Rust Version
    uses: dinglebear-ai/workflows/.github/workflows/rust-msrv.yml@eb5f36cf517ffc949aca1c81e2ccbc71b5a85267
    with:
      msrv: "1.97.1"
      command: cargo check --all-targets --locked && cargo test --no-run --all-targets --locked
