name: MSRV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  msrv:
    name: Minimum Supported Rust Version
    uses: dinglebear-ai/workflows/.github/workflows/rust-msrv.yml@542ea7b7e5ca2d4e21f3277bfcf158584fee90ec
    with:
      msrv: "1.97.1"
      command: cargo check --all-targets --locked && cargo test --no-run --all-targets --locked
